version: '3.8'

# Simplified Docker Compose for Integration Testing
# This extends the main docker-compose.yml with integration test specific settings

services:
  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper-integration
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'ruok' | nc localhost 2181"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka-integration
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      # Faster startup for testing
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_SEGMENT_BYTES: 1048576
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  # Mock GraphQL API for testing
  mock-graphql-api:
    build:
      context: ./test-graphql-api
      dockerfile: Dockerfile
    hostname: mock-graphql-api
    container_name: mock-graphql-api-integration
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Integration Test Runner
  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.integration
    container_name: integration-test-runner
    depends_on:
      kafka:
        condition: service_healthy
      mock-graphql-api:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      GRAPHQL_ENDPOINT: http://mock-graphql-api:4000/graphql
    volumes:
      - ./target:/app/target
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    profiles:
      - integration-tests

networks:
  default:
    name: integration-test-network